name: Run MAAS Terraform modules Nightly Tests

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC

jobs:
  run-full-test:
    runs-on: self-hosted-linux-amd64-noble-private-endpoint-medium
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Testflinger attachments
        run: ./testflinger.sh
        working-directory: tests
        env:
          SMOKE_TEST: false

      - name: Run on Testflinger
        uses: canonical/testflinger/.github/actions/submit@987fd7ab1467065217a9c6496eb2c3d85a250509
        with:
          poll: true
          job-path: ./tests/testflinger.yaml
          attachments-relative-to: ./tests/
